### ISSUE TITLE
[cord] Use Once Statements Pallet

### ISSUE THREAD

**Issue by NiranjanAP** [cord-network/community#11]
Use ONCE with 'statement' can be more clearly explained with an usecase of event ticket which is 'use once'. It can be true with flight tickets, museum tickets, event tickets etc.

So, think of a usecase, where any 'approved' applications can look at a statement (VC, PDF file, image etc), and if found valid, this app should be having a method to update the statement's status to 'Consumed' (or something similar). 

This way, the validity of tickets verification is logged on chain.

**Comment by amarts** [comment]
Pallet should contain mainly 2 methods. One which takes identifier as input argument, and in storage marks it in a table, another which takes the identifier, checks if its in storage, and also the addition is done by the given DID.

**Comment by NiranjanAP** [comment]
Created a duplicate in DMP format - https://github.com/cord-network/community/issues/17
